#!/usr/bin/env bash
set -e

if [ $EUID == 0 ]; then
    echo "This script must not be run as root"
    exit
fi

if ! [ -e "/opt/cathook/" ]; then
    echo "Please install Cathook on your main TF2, first."
    echo "https://cathook.club/s/ch/git"
    exit
fi

# Idiot proof this shit
if ! [ -d ".git" ]; then
    echo "You must clone the repo instead of downloading it."
    exit
fi

if [ ! -x "$(command -v touch)" ]; then
    echo "Touch doesn't exist. Please install it. (touch)"
    exit
fi

if [ ! -x "$(command -v route)" ] && [ ! -x /sbin/route ]; then
    echo "Route doesn't exist. Please install it. (net-tools)"
    exit
fi

if [ ! -x "$(command -v npm)" ]; then
    echo "NPM doesn't exist. Please install it. (npm)"
    exit
fi

if [ ! -x "$(command -v firejail)" ]; then
    echo "Firejail doesn't exist. Please install it. (firejail)"
    exit
fi

if [ ! -x "$(command -v pgrep)" ]; then
    echo "Pgrep doesn't exist. Please install it."
    exit
fi

./remove-legacy

if [ ! -d "./cathook" ]; then
    URL="$(curl --max-time 10 -Ls -o /dev/null -w %{url_effective} https://cathook.club/s/ch/git || echo error)"
    git clone --recursive $URL
fi

if [ -d ~/.steam/steam/steamapps/common/Team\ Fortress\ 2/tf/maps/ ]; then
    if [ -d ./catbot-database ]; then
        echo "Fetching navmeshes..."
        pushd catbot-database
        git fetch --depth 1
        git reset --hard origin/master
        popd
    else
        git clone --depth 1 https://github.com/nullworks/catbot-database
    fi

    echo "Copying navmeshes..."
    rsync catbot-database/nav\ meshes/*.nav ~/.steam/steam/steamapps/common/Team\ Fortress\ 2/tf/maps/
    chmod 755 ~/.steam/steam/steamapps/common/Team\ Fortress\ 2/tf/maps/*.nav # fixup permissions so tf2 is happy
fi

mkdir -p user_instances

if [ ! -f /opt/cathook/bin/libcathook-textmode.so ]; then
    numcpu=$(grep -c ^processor /proc/cpuinfo)
    mkdir -p build
    pushd build
    cmake -DCMAKE_BUILD_TYPE=Release -DVisuals_DrawType="Textmode" -DVACBypass=1 -DEnableWarnings=0 ../cathook/
    make -j$numcpu
    if ! [ -e "bin/libcathook.so" ]; then
        echo "FATAL: Build failed"
        exit
    fi
    popd
    sudo mkdir -p "/opt/cathook/bin/"
    sudo mkdir -p "/opt/cathook/data/configs"
    sudo cp "build/bin/libcathook.so" "/opt/cathook/bin/libcathook-textmode.so"
    sudo chmod -R 0755 /opt/cathook/data/configs/
fi

if [ ! -d "./just-disable-vac" ]; then
    git clone https://gitlab.com/nullworks/cathook/just-disable-vac
    pushd just-disable-vac
    mkdir -p build && pushd build
    cmake .. && make
    popd; popd
fi

if [ ! -d "./cathook-ipc-server" ]; then
    git clone --recursive https://github.com/nullworks/cathook-ipc-server
    pushd cathook-ipc-server
    ./install.sh
    popd
fi

if [ ! -d "./cathook-ipc-web-panel" ]; then
    git clone --recursive https://github.com/nullworks/cathook-ipc-web-panel
    pushd cathook-ipc-web-panel
    ./update.sh
    popd
fi

if [ ! -d "./nullnexus-proxy" ]; then
    git clone --recursive https://gitlab.com/nullworks/cathook/nullnexus-proxy
    pushd nullnexus-proxy
    ./update.sh
    popd
fi

if [ ! -d "./cathook-ipc-web-panel/logs" ]; then
    mkdir -p ./cathook-ipc-web-panel/logs
    touch ./cathook-ipc-web-panel/logs/main.log
fi

sudo sed -i 's/^restricted-network yes/# restricted-network yes/g' /etc/firejail/firejail.config

echo "Installation finished. Please ensure that all navmashes are inside your map folder (see https://github.com/nullworks/cathook/catbot-database)."
echo
echo "The web-panel and account storage can be started with ./start"
echo
echo "Accgen is broken due to recent recaptcha updates, as well as us running out of accounts to provide. You must create your own list of accounts to use for catbots."
echo "Create a list of steam accounts, and save them to catbot-setup/accounts.txt in username:password format."
