#!/bin/bash

#
#       This script starts IPC server, account generator, etc..
#

if [ $EUID == 0 ]; then
    echo "This script must not be run as root"
    exit
fi

if ! [ -d "./account-generator" ]; then
	echo "You need to run install-catbots first."
	exit
fi

if [ ! -x "$(command -v Xvfb)" ]; then
    echo "Xvfb doesn't exist. Please install it."
    exit
fi

xhost +

ipcserver=$( ps faux | grep '/opt/cathook/ipc/bin/server' | grep -vw grep | awk '{ print $2 }' );
[ -z "$ipcserver" ] && /opt/cathook/ipc/bin/server -s >/dev/null &
[ -z "$ipcserver" ] && echo $! >/tmp/cat-ipc-server.pid

if [ -e "/tmp/ncat-cathook-webpanel.pid" ] && ps -p `cat "/tmp/ncat-cathook-webpanel.pid"` >/dev/null; then
    echo Account generator already running.
else
    pushd cathook-ipc-web-panel
    sudo STEAM_LD_PRELOAD="$(cd ../ && pwd)/just-disable-vac/build/bin64/libvpcfs.so.0:$(cd ../ && pwd)/just-disable-vac/build/bin32/libvpcfs.so.0" bash ./run.sh &
    popd
fi

if [ -e "/tmp/ncat-account-generator.pid" ] && ps -p `cat "/tmp/ncat-account-generator.pid"` >/dev/null; then
    echo Account generator already running.
else
    pushd account-generator
    node app >/tmp/cathook-accgen.log &
    popd
fi
if [ -e "/tmp/cat-Xvfb.pid" ] && ps -p `cat "/tmp/cat-Xvfb.pid"` >/dev/null; then
    echo Xvfb already running.
else
    Xvfb :3239 +extension GLX >/dev/null &
    echo $! > /tmp/cat-Xvfb.pid
fi

if [ -x "$(command -v pulseaudio)" ]; then
    echo "Starting Pulseaudio daemons"
    for i in $(seq 1 $(cat users))
    do
        sudo su - $(cat kisak)-$i -c "pulseaudio --daemonize=yes"
    done
fi

sleep 5;

echo "Account generator password: `cat /tmp/cat-accgen2-password`"
echo "IPC Web Panel password: `cat /tmp/cat-webpanel-password`"

echo "Fixing NVIDIA crash"
sudo chmod 700 /opt/steamapps/common/Team\ Fortress\ 2/tf/glshaders.cfg
echo "Fixed NVIDIA crash"

echo "Creating namespaces"
sudo ./scripts/ns-create $(cat ./users);
echo "Done!"
