#!/bin/bash

#
#       This script starts IPC server, account generator, etc..
#

if [ $EUID == 0 ]; then
    echo "This script must not be run as root"
    exit
fi

if ! [ -d "./account-generator" ]; then
	echo "You need to run install-catbots first."
	exit
fi

xhost +

ipcserver=$( ps faux | grep '/opt/cathook/ipc/bin/server' | grep -vw grep | awk '{ print $2 }' );
[ -z "$ipcserver" ] && /opt/cathook/ipc/bin/server -s >/dev/null &
[ -z "$ipcserver" ] && echo $! >/tmp/cat-ipc-server.pid

if [ -e "/tmp/ncat-cathook-webpanel.pid" ] && ps -p `cat "/tmp/ncat-cathook-webpanel.pid"` >/dev/null; then
    echo Account generator already running.
else
    pushd cathook-ipc-web-panel
    sudo STEAM_LD_PRELOAD="$(cd ../ && pwd)/just-disable-vac/build/bin64/libvpcfs.so.0:$(cd ../ && pwd)/just-disable-vac/build/bin32/libvpcfs.so.0" bash ./run.sh &
    popd
fi

if [ -e "/tmp/ncat-account-generator.pid" ] && ps -p `cat "/tmp/ncat-account-generator.pid"` >/dev/null; then
    echo Account generator already running.
else
    pushd account-generator
    node app >/tmp/cathook-accgen.log &
    popd
fi

if [ -x "$(command -v pulseaudio)" ]; then
    echo "Setting up Pulseaudio socket"
    pactl load-module module-native-protocol-unix auth-anonymous=1 socket=/tmp/pulse.sock > /tmp/pulsemodule.id
fi

sleep 5;

echo "Account generator password: `cat /tmp/cat-accgen2-password`"
echo "IPC Web Panel password: `cat /tmp/cat-webpanel-password`"

echo "Fixing NVIDIA crash"
sudo chmod 700 /opt/steamapps/common/Team\ Fortress\ 2/tf/glshaders.cfg
echo "Fixed NVIDIA crash"

echo "Creating namespaces"
sudo ./scripts/ns-create $(cat ./users);
echo "Done!"
