#!/bin/bash

#
#       This script stops all processes of steam and TF2
#

[ -f /tmp/cat-ipc-server.pid ] && sudo kill $(cat /tmp/cat-ipc-server.pid)
[ -f /tmp/ncat-cathook-webpanel.pid ] && PID="$(cat /tmp/ncat-cathook-webpanel.pid)" && sudo kill -SIGINT "$PID" && tail --pid="$PID" -f /dev/null

[ -f /tmp/ncat-cathook-webpanel.pid ] && sudo rm /tmp/ncat-cathook-webpanel.pid
[ -f /tmp/cat-ipc-server.pid ] && sudo rm /tmp/cat-ipc-server.pid

ipcserver=$( ps faux | grep '/opt/cathook/ipc/bin/server' | grep -vw grep | awk '{ print $2 }' );
[ ! -z "$ipcserver" ] && sudo kill ${ipcserver};
ipcconsole=$( ps faux | grep '/opt/cathook/ipc/bin/console' | grep -vw grep | awk '{ print $2 }' );
[ ! -z "$ipcconsole" ] && sudo kill ${ipcconsole};
