#!/usr/bin/env bash

function updateRepoURL() {
    local URL="$(curl --max-time 10 -Ls -o /dev/null -w %{url_effective} https://cathook.club/s/ch/git || echo error)"
    local GIT_REMOTE=$(git config --get remote.origin.url || echo unknown)
    if [ "$URL" != "error" ] && [ "$GIT_REMOTE" != "$URL" ]; then
        git remote set-url origin "$URL"
        echo -e "\033[1;33m\n\nMigrations: Updated remote URL to new repo! Welcome to $URL!\n\n\033[0m"
    fi
}

git pull
pushd cathook

GIT_REMOTE=$(git config --get remote.origin.url || echo unknown)
if [ "$GIT_REMOTE" == "https://github.com/nullworks/cathook.git" ] || [ "$GIT_REMOTE" == "https://github.com/nullworks/cathook" ]; then
    updateRepoURL
fi


git pull
git submodule update --init --recursive
popd
mkdir -p build
pushd build
cmake -DCMAKE_BUILD_TYPE=Release -DVisuals_DrawType="Textmode" -DVACBypass=1 -DEnableWarnings=0 -DEnableOnlineFeatures=0 ../cathook/
numcpu=$(grep -c ^processor /proc/cpuinfo)
make -j$numcpu
if ! [ -e "bin/libcathook.so" ]; then
    echo "FATAL: Build failed"
    exit
fi
popd
sudo mkdir -p "/opt/cathook/bin/"
sudo cp "build/bin/libcathook.so" "/opt/cathook/bin/libcathook-textmode.so"

pushd cathook-ipc-server
bash update.sh
popd

pushd cathook-ipc-web-panel
bash update.sh
popd

pushd account-generator
bash update.sh
popd
