#!/usr/bin/env bash

OLD_UPDATE=$(git rev-parse HEAD:update)
git pull --ff
NEW_UPDATE=$(git rev-parse HEAD:update)

if [ $OLD_UPDATE != $NEW_UPDATE ]; then
    echo Update script self update!
    exec $0 $@
fi

function updateRepoURL() {
    local URL="$(curl --max-time 10 -Ls -o /dev/null -w %{url_effective} https://cathook.club/s/ch/git || echo error)"
    local GIT_REMOTE=$(git config --get remote.origin.url || echo unknown)
    if [ "$URL" != "error" ] && [ "$GIT_REMOTE" != "$URL" ]; then
        git remote set-url origin "$URL"
        echo -e "\033[1;33m\n\nMigrations: Updated remote URL to new repo! Welcome to $URL!\n\n\033[0m"
    fi
}

pushd cathook

GIT_REMOTE=$(git config --get remote.origin.url || echo unknown)
if [ "$GIT_REMOTE" == "https://github.com/nullworks/cathook.git" ] || [ "$GIT_REMOTE" == "https://github.com/nullworks/cathook" ]; then
    updateRepoURL
fi


git pull --ff
git submodule update --init --recursive
popd
mkdir -p build
pushd build
cmake -DCMAKE_BUILD_TYPE=Release -DVisuals_DrawType="Textmode" -DVACBypass=1 -DEnableWarnings=0 ../cathook/
numcpu=$(grep -c ^processor /proc/cpuinfo)
make -j$numcpu
if ! [ -e "bin/libcathook.so" ]; then
    echo "FATAL: Build failed"
    exit
fi
popd
sudo mkdir -p "/opt/cathook/bin/"
sudo cp "build/bin/libcathook.so" "/opt/cathook/bin/libcathook-textmode.so"

pushd cathook-ipc-server
git remote set-url origin https://github.com/nullworks/cathook-ipc-server
bash update.sh
popd

pushd nullnexus-proxy
git remote set-url origin https://gitlab.com/nullworks/cathook/nullnexus-proxy
bash update.sh
popd

pushd cathook-ipc-web-panel
git remote set-url origin https://github.com/nullworks/cathook-ipc-web-panel
bash update.sh
popd


echo "Fetching navmeshes..."
if [ -d ./catbot-database ]; then
	pushd catbot-database
	git fetch --depth 1
	git reset --hard origin/master
	popd
else
	git clone --depth 1 https://github.com/nullworks/catbot-database
fi

echo "Copying navmeshes..."
rsync catbot-database/nav\ meshes/*.nav ~/.steam/steam/steamapps/common/Team\ Fortress\ 2/tf/maps/
chmod 755 ~/.steam/steam/steamapps/common/Team\ Fortress\ 2/tf/maps/*.nav # fixup permissions so tf2 is happy

echo "Done."
